insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1953-11-29','Insurance Clerk','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2012-11-29','Mortarman','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1972-11-14','Beer Coil Cleaner','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2013-01-01','Scale Attendant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1971-03-01','Clinical Audiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1936-11-26','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1966-07-01','Business Unit Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2009-05-11','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1958-07-16','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1945-06-22','Food Chemist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1981-08-03','Signals Intelligence/Electronic Warfare Chief','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1942-06-04','Language Pathologist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1957-06-03','Wildlife Officer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2008-03-14','Bindery Machine Operator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1929-03-10','Instructional Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1948-08-17','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1974-06-13','Mortician Investigator','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1948-10-08','Rod Buster Helper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1931-11-01','Classroom Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1933-05-13','Traditional Chinese Herbalist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1949-10-14','Electronic Drafter','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2014-03-08','Vault Teller','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1995-03-24','Fire Sprinkler Installer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1973-09-25','Brewery Pumper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1986-11-13','Kitchen Chef','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1966-01-04','Medical Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1935-06-10','Auto Tire Worker','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1932-09-17','Semi-Truck Driver','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1946-08-01','Command And Control','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1928-09-13','Drywall Hanger','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2008-10-01','Real Property Evaluator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1972-10-09','Human Performance Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1958-04-28','V/Stol Landing Signal Officer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1992-03-03','Air Control/Anti-Air Warfare Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1943-10-29','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2013-11-22','Child Protective Services Social Worker','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1944-09-05','Lens Grinder and Polisher','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1940-03-24','Civil Engineering Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1929-07-04','Mobile Home Servicer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1991-06-08','Floor Refinisher','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1954-08-30','Senior Sales Associate','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1987-11-02','Tile Designer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1940-12-11','Econometrics Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1993-10-04','Basketball Player','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1933-09-25','Indirect Fire Infantryman','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1963-10-09','Licensed Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1956-08-06','Antisubmarine Warfare Intelligence Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2018-04-02','Research Assistant','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1957-10-12','Cigar Roller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2008-07-31','Customer Support Representative','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2014-03-12','Programmer','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1977-07-16','Global Engineering Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1943-05-10','Telegraph and Teletype Operator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1987-10-17','Hairpiece Stylist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1973-04-06','Tobacco Buyer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1971-02-01','Marine Steamfitter','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1928-07-12','Attending Anesthesiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1967-04-12','Certified Indoor Environmentalist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1971-02-22','Land Management Forester','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1935-11-30','Digital Proofing and Platemaker','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1941-03-25','Public Health Veterinarian','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2016-09-02','Statement Processor','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2010-06-19','Computer Applications Developer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1969-04-11','African History Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1981-07-15','Gastroenterology Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1972-05-07','Laboratory Animal Caretaker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1981-04-08','Water Pump Installer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1949-01-18','Orthopedic Cast Specialist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1969-05-21','Budget Coordinator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1947-10-31','Railroad Engineer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1983-05-05','Chief Projectionist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1926-10-22','Telecasting Engineer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1934-11-02','Drama Therapist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1954-08-10','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1936-10-11','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1962-07-28','Leisure Studies Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1958-01-28','Air Conditioning Service Technician','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1928-10-23','Business Unit Manager','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2012-02-17','Job Estimator','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2001-02-08','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1938-10-11','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1930-07-08','Signals Intelligence/Electronic Warfare Chief','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1927-07-20','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1980-10-22','Wildlife Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1973-04-01','Food Chemist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2012-06-05','Advanced Foreign Counterintelligence Specialist (Afcs)','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1939-03-29','Forest Fire Officer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2013-07-11','Catalogue Illustrator','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1945-06-05','Knife Grinder','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2000-03-27','Neuropsychiatrist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2001-09-07','Bottle Packer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2018-09-10','Special Education Kindergarten Teacher','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2008-02-17','Commercial Art Instructor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2019-12-15','Ferryboat Captain','Supervisor',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2013-02-25','School Social Worker','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1990-02-09','Joint Terminal Attack Controller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2022-03-01','VP Sales','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1987-07-10','Auto Service Station Attendant','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1968-11-21','Healthcare Social Worker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1970-12-11','Comedian','External',false)
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 1,'697','jigrormo','697','697','jigrormo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 2,'107','zun','107','107','zun')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 3,'507','capfad','507','507','capfad')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 4,'106','dec','106','106','dec')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 5,'524','bivo','524','524','bivo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 6,'867','judbilo','867','867','judbilo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 7,'571','joraf','571','571','joraf')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 8,'142','kem','142','142','kem')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 9,'651','odeter','651','651','odeter')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 10,'781','lisohuje','781','781','lisohuje')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 11,'420','duod','420','420','duod')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 12,'812','nowufpus','812','812','nowufpus')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 13,'662','kagu','662','662','kagu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 14,'154','fef','154','154','fef')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 15,'944','derwogi','944','944','derwogi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 16,'750','wehovuce','750','750','wehovuce')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 17,'491','zamum','491','491','zamum')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 18,'748','dunebuh','748','748','dunebuh')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 19,'918','repiwid','918','918','repiwid')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 20,'903','razuppa','903','903','razuppa')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 21,'738','kulmenim','738','738','kulmenim')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 22,'94','ib','94','94','ib')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 23,'284','ba','284','284','ba')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 24,'499','tohhij','499','499','tohhij')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 25,'367','tuvo','367','367','tuvo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 26,'576','foga','576','576','foga')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 27,'882','uswuzzub','882','882','uswuzzub')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 28,'909','hivwerip','909','909','hivwerip')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 29,'770','gugusu','770','770','gugusu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 30,'949','zedekak','949','949','zedekak')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 31,'148','ral','148','148','ral')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 32,'508','turuhu','508','508','turuhu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 33,'653','omjo','653','653','omjo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 34,'314','rig','314','314','rig')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 35,'798','sicewap','798','798','sicewap')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 36,'97','fo','97','97','fo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 37,'789','gegijap','789','789','gegijap')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 38,'834','kuvesa','834','834','kuvesa')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 39,'941','lapahu','941','941','lapahu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 40,'322','zev','322','322','zev')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 41,'689','nabeaga','689','689','nabeaga')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 42,'357','kaot','357','357','kaot')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 43,'827','tawuctuj','827','827','tawuctuj')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 44,'298','eh','298','298','eh')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 45,'899','fajjusuz','899','899','fajjusuz')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 46,'598','pave','598','598','pave')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 47,'670','ispaviw','670','670','ispaviw')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 48,'53','ha','53','53','ha')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 49,'658','iliat','658','658','iliat')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 50,'150','do','150','150','do')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 51,'94','wi','94','94','wi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 52,'461','iwage','461','461','iwage')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 53,'803','joopoju','803','803','joopoju')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 54,'358','gojawu','358','358','gojawu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 55,'503','afigoh','503','503','afigoh')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 56,'525','benom','525','525','benom')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 57,'951','jevakbe','951','951','jevakbe')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 58,'563','darhow','563','563','darhow')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 59,'525','dupid','525','525','dupid')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 60,'877','comouc','877','877','comouc')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 61,'824','igunisi','824','824','igunisi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 62,'69','pe','69','69','pe')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 63,'131','puk','131','131','puk')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 64,'543','vegub','543','543','vegub')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 65,'421','rucwi','421','421','rucwi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 66,'512','agijit','512','512','agijit')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 67,'423','loolu','423','423','loolu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 68,'746','tupwovali','746','746','tupwovali')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 69,'542','hidge','542','542','hidge')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 70,'758','liowci','758','758','liowci')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 71,'402','vesa','402','402','vesa')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 72,'968','wupikdoh','968','968','wupikdoh')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 73,'888','dajsiphaj','888','888','dajsiphaj')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 74,'690','soofpe','690','690','soofpe')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 75,'868','aruzusjas','868','868','aruzusjas')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 76,'610','ufeco','610','610','ufeco')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 77,'655','uneehi','655','655','uneehi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 78,'948','hahinaba','948','948','hahinaba')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 79,'114','zun','114','114','zun')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 80,'225','jo','225','225','jo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 81,'848','goltuefo','848','848','goltuefo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 82,'931','lupuwuzo','931','931','lupuwuzo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 83,'961','reduzris','961','961','reduzris')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 84,'428','pubsav','428','428','pubsav')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 85,'503','lullip','503','503','lullip')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 86,'111','aba','111','111','aba')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 87,'844','kettujwo','844','844','kettujwo')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 88,'100','ju','100','100','ju')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 89,'782','vioburez','782','782','vioburez')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 90,'233','ig','233','233','ig')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 91,'219','omu','219','219','omu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 92,'49','luw','49','49','luw')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 93,'154','pi','154','154','pi')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 94,'36','zu','36','36','zu')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 95,'104','ag','104','104','ag')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 96,'335','fopav','335','335','fopav')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 97,'14','ji','14','14','ji')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 98,'361','lojet','361','361','lojet')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 99,'547','ukve','547','547','ukve')
insert into producto(version, id,id_producto,nombre,precio,stock,proovedor) values (1, 100,'527','viipo','527','527','viipo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 1,'697','jigrormo','(762) 526-5961','jigrormo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 2,'107','zun','(267) 955-5124','zun')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 3,'507','capfad','(680) 368-2192','capfad')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 4,'106','dec','(281) 301-2039','dec')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 5,'524','bivo','(600) 616-7955','bivo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 6,'867','judbilo','(882) 813-1374','judbilo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 7,'571','joraf','(642) 665-1763','joraf')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 8,'142','kem','(383) 458-2132','kem')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 9,'651','odeter','(769) 335-6771','odeter')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 10,'781','lisohuje','(803) 586-8035','lisohuje')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 11,'420','duod','(531) 919-2280','duod')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 12,'812','nowufpus','(814) 667-8937','nowufpus')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 13,'662','kagu','(713) 311-8766','kagu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 14,'154','fef','(381) 421-2371','fef')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 15,'944','derwogi','(940) 463-7299','derwogi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 16,'750','wehovuce','(777) 435-9570','wehovuce')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 17,'491','zamum','(517) 393-9630','zamum')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 18,'748','dunebuh','(711) 904-3669','dunebuh')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 19,'918','repiwid','(935) 404-4792','repiwid')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 20,'903','razuppa','(935) 267-8492','razuppa')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 21,'738','kulmenim','(763) 948-4815','kulmenim')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 22,'94','ib','(238) 240-2561','ib')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 23,'284','ba','(410) 257-1723','ba')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 24,'499','tohhij','(566) 726-3346','tohhij')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 25,'367','tuvo','(416) 906-7221','tuvo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 26,'576','foga','(611) 712-1562','foga')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 27,'882','uswuzzub','(919) 887-8542','uswuzzub')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 28,'909','hivwerip','(982) 684-7650','hivwerip')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 29,'770','gugusu','(811) 931-8202','gugusu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 30,'949','zedekak','(927) 400-3928','zedekak')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 31,'148','ral','(365) 345-1498','ral')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 32,'508','turuhu','(656) 968-9869','turuhu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 33,'653','omjo','(739) 612-6585','omjo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 34,'314','rig','(485) 521-2687','rig')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 35,'798','sicewap','(835) 620-3330','sicewap')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 36,'97','fo','(211) 851-5960','fo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 37,'789','gegijap','(811) 311-5257','gegijap')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 38,'834','kuvesa','(843) 836-3759','kuvesa')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 39,'941','lapahu','(913) 235-1856','lapahu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 40,'322','zev','(467) 487-7239','zev')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 41,'689','nabeaga','(724) 340-3634','nabeaga')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 42,'357','kaot','(413) 229-8428','kaot')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 43,'827','tawuctuj','(886) 292-9749','tawuctuj')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 44,'298','eh','(418) 472-1239','eh')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 45,'899','fajjusuz','(961) 233-3461','fajjusuz')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 46,'598','pave','(605) 226-4037','pave')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 47,'670','ispaviw','(719) 765-1705','ispaviw')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 48,'53','ha','(232) 228-5539','ha')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 49,'658','iliat','(768) 554-8377','iliat')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 50,'150','do','(311) 731-7079','do')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 51,'94','wi','(207) 554-6244','wi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 52,'461','iwage','(558) 913-2855','iwage')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 53,'803','joopoju','(832) 759-6654','joopoju')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 54,'358','gojawu','(482) 736-8079','gojawu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 55,'503','afigoh','(677) 345-2680','afigoh')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 56,'525','benom','(610) 374-7581','benom')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 57,'951','jevakbe','(982) 583-8067','jevakbe')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 58,'563','darhow','(680) 266-3167','darhow')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 59,'525','dupid','(611) 955-4652','dupid')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 60,'877','comouc','(940) 714-8088','comouc')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 61,'824','igunisi','(868) 481-5125','igunisi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 62,'69','pe','(225) 395-2772','pe')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 63,'131','puk','(365) 837-6888','puk')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 64,'543','vegub','(606) 352-8734','vegub')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 65,'421','rucwi','(555) 800-7339','rucwi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 66,'512','agijit','(657) 357-3671','agijit')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 67,'423','loolu','(523) 789-5485','loolu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 68,'746','tupwovali','(766) 966-7387','tupwovali')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 69,'542','hidge','(672) 613-2954','hidge')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 70,'758','liowci','(803) 549-9387','liowci')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 71,'402','vesa','(526) 435-1819','vesa')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 72,'968','wupikdoh','(937) 855-5936','wupikdoh')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 73,'888','dajsiphaj','(960) 335-6192','dajsiphaj')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 74,'690','soofpe','(735) 809-2611','soofpe')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 75,'868','aruzusjas','(857) 797-7918','aruzusjas')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 76,'610','ufeco','(659) 331-1543','ufeco')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 77,'655','uneehi','(759) 639-8597','uneehi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 78,'948','hahinaba','(942) 352-4854','hahinaba')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 79,'114','zun','(247) 867-8287','zun')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 80,'225','jo','(302) 793-9936','jo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 81,'848','goltuefo','(861) 740-6628','goltuefo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 82,'931','lupuwuzo','(953) 866-9992','lupuwuzo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 83,'961','reduzris','(915) 491-8384','reduzris')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 84,'428','pubsav','(584) 909-6235','pubsav')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 85,'503','lullip','(673) 849-4256','lullip')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 86,'111','aba','(268) 208-9643','aba')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 87,'844','kettujwo','(873) 489-6641','kettujwo')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 88,'100','ju','(243) 974-5539','ju')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 89,'782','vioburez','(816) 699-1291','vioburez')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 90,'233','ig','(319) 401-1090','ig')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 91,'219','omu','(359) 691-6408','omu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 92,'49','luw','(273) 892-4646','luw')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 93,'154','pi','(304) 610-2881','pi')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 94,'36','zu','(237) 969-2900','zu')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 95,'104','ag','(207) 424-6468','ag')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 96,'335','fopav','(481) 661-8179','fopav')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 97,'14','ji','(212) 510-3444','ji')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 98,'361','lojet','(433) 862-3076','lojet')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 99,'547','ukve','(619) 506-4452','ukve')
insert into clientes(version, id,cedula,nombre,telefono,direccion) values (1, 100,'527','viipo','(616) 688-6883','viipo')
